### ISSUE TITLE
予約録音が開始されない

### ISSUE THREAD

**Issue by im-not-enemy** [im-not-enemy/radio-base#6]
```
[2020-01-01T18:33:30.489] [DEBUG] system - 予約録音完了 => id:9510800358
```

**Comment by im-not-enemy** [comment]
原因特定のため、ログをより詳細にとるようにしてみる。

**Comment by im-not-enemy** [comment]
NodeScheduleのジョブによって、指定した時間にRecordingBot.start()が呼び出されると、下記のエラーが発生
```
(node:4420) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'program' of undefined
    at /home/flog/radio-base/lib/Application/Bots/RecordingBot.js:28:41
    at Generator.next (<anonymous>)
    at /home/flog/radio-base/lib/Application/Bots/RecordingBot.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/flog/radio-base/lib/Application/Bots/RecordingBot.js:4:12)
    at start (/home/flog/radio-base/lib/Application/Bots/RecordingBot.js:27:16)
    at Job.job (/home/flog/radio-base/lib/Application/ScheduleManagers/NodeScheduler.js:23:71)
    at Job.invoke (/home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:173:10)
    at /home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:552:11
    at Timeout._onTimeout (/home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:510:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:4420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by im-not-enemy** [comment]
RecordingBotのクラス変数programにアクセスできていない模様。

**Comment by im-not-enemy** [comment]
クラス変数にアクセスしようとしなければ、RecordingBot.start()を実行すること自体に問題はない。
例として下記のコードは成功する。
```
    public async start():Promise<{[key:string]:any}>{
        console.log(new Date())
        return {succeed:true}
        /*
        const result = this.program.canStartRecording()
        if (result.succeed === false) return result
        this.tapeRecorder.tuneTo(this.program.toStringStation())
        this.tapeRecorder.setTimer(this.program.calculateDuration())
        this.tapeRecorder.writeNameToTape(`${this.program.toStringStation()}_${this.program.toStringTitle()}_${this.program.toStringStartTime()}`)
        await this.tapeRecorder.pushStartButton()
        return result
        */
    }
```

**Comment by im-not-enemy** [comment]
サンプルコードでも事象が再現。
this.が使えない模様。
```
import moment from 'moment'

export default class Sample {
    private property:string
    constructor(property:string){
        this.property = property
    }
    public wtest(){
        this.test() ★失敗
    }
    public mtest(){
        console.log(`${moment(new Date()).format('YYYY-MM-DD-HH:mm:ss')}`) ☆成功
    }
    public test(){
        console.log(`${new Date()}`) ☆成功
    }
    public ptest(){
        console.log(`${new Date()}:${this.property}`) ★失敗
    }
    public async testAsync(){
        console.log(`${new Date()}`) ☆成功
    }
    public async ptestAsync(){
        console.log(`${new Date()}:${this.property}`) ★失敗
    }
}
```

**Comment by im-not-enemy** [comment]
呼び出し側で newを関数でラップすると成功する
```
import NodeScheduleTest from './NodeScheduleTest'
import Sample from './Sample'

const nodeScheduleTest = new NodeScheduleTest()

const func = () => {
    const sample = new Sample('test')
    sample.ptestAsync()
}
nodeScheduleTest.activate('* * * * * *',func)
```

**Comment by im-not-enemy** [comment]
ラップした関数内でthis.を使おうとすると失敗する
```
import NodeScheduleTest from './NodeScheduleTest'
import Sample from './Sample'

export default class Client {
    private nodeScheduleTest = new NodeScheduleTest()
    private message = 'test'
    private func(){
        const sample = new Sample(this.message)
        sample.ptestAsync()
    }
    public request(){
        this.nodeScheduleTest.activate('* * * * * *',this.func)
    }
}
```
↓
```
TypeError: Cannot read property 'message' of undefined
    at func (/home/flog/radio-base/lib/Test/Client.js:14:50)
    at Job.job (/home/flog/radio-base/lib/Test/NodeScheduleTest.js:9:59)
    at Job.invoke (/home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:173:10)
    at /home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:552:11
    at Timeout._onTimeout (/home/flog/radio-base/node_modules/node-schedule/lib/schedule.js:510:7)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
